#! /bin/bash

autocomplete()
{
	local NOTES_ROOT CUR 
	NOTES_ROOT='~/Notes'
	CUR="${COMP_WORDS[$COMP_CWORD]}"
	if [ "${#COMP_WORDS[@]}" = "2" ]; then
		COMPREPLY=($(compgen -W "add load open" "${COMP_WORDS[1]}"))
	elif [ "${#COMP_WORDS[@]}" = "3" ]; then
		COMPREPLY=($(compgen -W "note notebook journal" "${COMP_WORDS[2]}"))
	elif [ "${#COMP_WORDS[@]}" = "4" ]; then
		if [  "${COMP_WORDS[$COMP_CWORD -1]}" = "notebook" ]; then
			compopt -o nospace -o plusdirs 
			if [[ "$CUR" == "$NOTES_ROOT"* ]]; then 
				compopt -o nospace -o plusdirs
				COMPREPLY=($(compgen  -d -- "$CUR"  "${COMP_WORDS[4]}"))
			else
				compopt -o nospace -o dirnames
				COMPREPLY=($(compgen -d -- "$NOTES_ROOT/"  "${COMP_WORDS[4]}"))
			fi

			suggestions=$(compgen  -d  "$NOTES_ROOT/$CUR"  "${COMP_WORDS[4]}")
			newsug=()
			for suggestion in "$suggestions"; do 
				#newsug+=${suggestion##*(~/Notes/)}
				newsug+=`echo "$suggestions" | sed 's|.*/||g'`
			done
			COMPREPLY=(${newsug})
		elif [  "${COMP_WORDS[$COMP_CWORD -1]}" = "note" ]; then
			if [[ "$CUR" == "$NOTES_ROOT"* ]]; then 
				compopt -o nospace -o plusdirs
				COMPREPLY=($(compgen  -f -- "$CUR"  "${COMP_WORDS[4]}"))
			else
				compopt -o nospace -o dirnames
				COMPREPLY=($(compgen -f -- "$NOTES_ROOT/"  "${COMP_WORDS[4]}"))
			fi
		fi

	fi

}

#-o nospace 
complete -F autocomplete  mynotes 
